/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesButtonsIndexRouteImport } from './routes/pages/Buttons/index'
import { Route as PagesButtonsButtonExampleRouteImport } from './routes/pages/Buttons/ButtonExample'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesButtonsIndexRoute = PagesButtonsIndexRouteImport.update({
  id: '/pages/Buttons/',
  path: '/pages/Buttons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesButtonsButtonExampleRoute =
  PagesButtonsButtonExampleRouteImport.update({
    id: '/pages/Buttons/ButtonExample',
    path: '/pages/Buttons/ButtonExample',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/Buttons/ButtonExample': typeof PagesButtonsButtonExampleRoute
  '/pages/Buttons': typeof PagesButtonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/Buttons/ButtonExample': typeof PagesButtonsButtonExampleRoute
  '/pages/Buttons': typeof PagesButtonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages/Buttons/ButtonExample': typeof PagesButtonsButtonExampleRoute
  '/pages/Buttons/': typeof PagesButtonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages/Buttons/ButtonExample' | '/pages/Buttons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages/Buttons/ButtonExample' | '/pages/Buttons'
  id: '__root__' | '/' | '/pages/Buttons/ButtonExample' | '/pages/Buttons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesButtonsButtonExampleRoute: typeof PagesButtonsButtonExampleRoute
  PagesButtonsIndexRoute: typeof PagesButtonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/Buttons/': {
      id: '/pages/Buttons/'
      path: '/pages/Buttons'
      fullPath: '/pages/Buttons'
      preLoaderRoute: typeof PagesButtonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/Buttons/ButtonExample': {
      id: '/pages/Buttons/ButtonExample'
      path: '/pages/Buttons/ButtonExample'
      fullPath: '/pages/Buttons/ButtonExample'
      preLoaderRoute: typeof PagesButtonsButtonExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesButtonsButtonExampleRoute: PagesButtonsButtonExampleRoute,
  PagesButtonsIndexRoute: PagesButtonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
