/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as PagesButtonsIndexRouteImport } from './routes/pages/buttons/index'
import { Route as PagesButtonsButtonExampleRouteImport } from './routes/pages/buttons/ButtonExample'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesButtonsIndexRoute = PagesButtonsIndexRouteImport.update({
  id: '/pages/buttons/',
  path: '/pages/buttons/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesButtonsButtonExampleRoute =
  PagesButtonsButtonExampleRouteImport.update({
    id: '/pages/buttons/ButtonExample',
    path: '/pages/buttons/ButtonExample',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages': typeof PagesIndexRoute
  '/pages/buttons/ButtonExample': typeof PagesButtonsButtonExampleRoute
  '/pages/buttons': typeof PagesButtonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages': typeof PagesIndexRoute
  '/pages/buttons/ButtonExample': typeof PagesButtonsButtonExampleRoute
  '/pages/buttons': typeof PagesButtonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages/': typeof PagesIndexRoute
  '/pages/buttons/ButtonExample': typeof PagesButtonsButtonExampleRoute
  '/pages/buttons/': typeof PagesButtonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages' | '/pages/buttons/ButtonExample' | '/pages/buttons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages' | '/pages/buttons/ButtonExample' | '/pages/buttons'
  id:
    | '__root__'
    | '/'
    | '/pages/'
    | '/pages/buttons/ButtonExample'
    | '/pages/buttons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesIndexRoute: typeof PagesIndexRoute
  PagesButtonsButtonExampleRoute: typeof PagesButtonsButtonExampleRoute
  PagesButtonsIndexRoute: typeof PagesButtonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/buttons/': {
      id: '/pages/buttons/'
      path: '/pages/buttons'
      fullPath: '/pages/buttons'
      preLoaderRoute: typeof PagesButtonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/buttons/ButtonExample': {
      id: '/pages/buttons/ButtonExample'
      path: '/pages/buttons/ButtonExample'
      fullPath: '/pages/buttons/ButtonExample'
      preLoaderRoute: typeof PagesButtonsButtonExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesIndexRoute: PagesIndexRoute,
  PagesButtonsButtonExampleRoute: PagesButtonsButtonExampleRoute,
  PagesButtonsIndexRoute: PagesButtonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
